name: chat_interface
description: Frontend for the Fajurion Chat Network.
publish_to: 'none'

version: 1.0.0-ALPHA

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_animate: any
  get: any
  path_provider: any
  path: any
  drift: any
  sqlite3_flutter_libs: any
  logger: any
  web_socket_channel: any
  crypto: any
  http: any
  animations: any
  pointycastle: any
  livekit_client: ^2.0.1
  logging: any
  url_launcher: any
  flutter_webrtc: any
  record: any
  sodium_libs: any
  ffi: any
  flutter_rust_bridge: 2.0.0-dev.22
  freezed_annotation: any
  file_selector: any
  drift_db_viewer: any
  smooth_scroll_multiplatform: any
  audioplayers: any
  dio: any
  encrypt: any
  open_app_file: any
  rust_builder:
    path: rust_builder
  unicode_emojis: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: any
  build_runner: any
  flutter_lints: any
  test: any
  ffigen: any
  freezed: any
  msix: any
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/OpenSans.ttf

  assets:
  - assets/img/
  - assets/music/

msix_config:
  display_name: The chat app
  publisher_display_name: Fajurion
  identity_name: com.fajurion.chat
  msix_version: 1.0.0.0
  logo_path: C:/Users/thisi/OneDrive/Bilder/Logos/chat.png
  capabilities: internetClient, microphone, webcam